apiVersion: v1
kind: Service
metadata:
  name: dev-minikube-position-service
  labels:
    app: dev-minikube-position-service
spec:
  type: NodePort
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: dev-minikube-position-service
