apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-position-postgres-pvc
  namespace: default
spec:
  storageClassName: ""
  volumeName: dev-position-postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi